### ISSUE TITLE
2D detector output from Total3D

### ISSUE THREAD

**Issue by stefan-ainetter** [chengzhag/Implicit3DUnderstanding#13]
Hi @chengzhag,
thanks for this great contribution!
It is stated in the paper that: "We use the outputs of the 2D detector from Total3D as the input of our model.". Does this mean that 1) you used the exact same model and pre-trained weights provided by Total3D, or 2)  you trained your own 2D detector in the same way as the authors of Total3D?

Furthermore, could you share this pre-computed 2D bounding boxes, or some instructions (model and weights if available) that makes it possible to re-produce the whole pipeline?

Thanks a lot in advance.

**Comment by chengzhag** [comment]
Hi @stefan-ainetter,

We used the pre-computed 2D bounding boxes provided by Total3D.
You can follow our instructions of "Data preparation" to download from their link.

**Comment by stefan-ainetter** [comment]
Thanks a lot!
