### ISSUE TITLE
Error while running the demo via ssh

### ISSUE THREAD

**Issue by Jit-INP** [chengzhag/Implicit3DUnderstanding#15]
/bin/sh: 1: /dev/shm/tmpmmweeyxx/ldif2mesh: Permission denied

subprocess.CalledProcessError: Command '/dev/shm/tmpmmweeyxx/ldif2mesh /dev/shm/tmpmmweeyxx/ldif.txt /dev/shm/tmpmmweeyxx/serialized.occnet /dev/shm/tmpmmweeyxx/grid.grd -resolution 128 -extent 0.7' returned non-zero exit status 126.

![Error](https://user-images.githubusercontent.com/59926833/157257098-0f970843-3c10-42f2-aa0b-6ef1cbe0157f.PNG)

**Comment by JiazheZhang** [comment]
hi，how did you solve the problem?

**Comment by yuyingyeh** [comment]
I solved this by changing the path below to a path that I have the permission to access.
https://github.com/chengzhag/Implicit3DUnderstanding/blob/517c0ffde9eff819fb663a93bcbee94949673ae4/models/total3d/modules/mesh_reconstruction.py#L410
