### ISSUE TITLE
Errors about the pyTorchChamferDistance

### ISSUE THREAD

**Issue by w1246410140** [chengzhag/Implicit3DUnderstanding#3]
Thanks for your great work! When I run the command `CUDA_VISIBLE_DEVICES=0 python main.py out/total3d/20110611514267/out_config.yaml --mode demo --demo_path demo/inputs/1` ,I get the following error:
①Traceback (most recent call last):
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 949, in _build_extension_module
    check=True)
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    import train, test,demo
  File "/home/data4t/wyf/Implicit3DUnderstanding/train.py", line 4, in <module>
    from models.optimizers import load_optimizer, load_scheduler
  File "/home/data4t/wyf/Implicit3DUnderstanding/models/__init__.py", line 1, in <module>
    from . import total3d, mgnet, ldif
  File "/home/data4t/wyf/Implicit3DUnderstanding/models/total3d/__init__.py", line 1, in <module>
    from . import modules, training, config, dataloader
  File "/home/data4t/wyf/Implicit3DUnderstanding/models/total3d/modules/__init__.py", line 1, in <module>
    from .network import TOTAL3D
  File "/home/data4t/wyf/Implicit3DUnderstanding/models/total3d/modules/network.py", line 12, in <module>
    from models.loss import get_phy_loss_samples
  File "/home/data4t/wyf/Implicit3DUnderstanding/models/loss.py", line 8, in <module>
    from external.pyTorchChamferDistance.chamfer_distance import ChamferDistance
  File "/home/data4t/wyf/Implicit3DUnderstanding/external/pyTorchChamferDistance/chamfer_distance/__init__.py", line 3, in <module>
    from .chamfer_distance import ChamferDistance
  File "/home/data4t/wyf/Implicit3DUnderstanding/external/pyTorchChamferDistance/chamfer_distance/chamfer_distance.py", line 8, in <module>
    build_directory="external/pyTorchChamferDistance/build")
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 813, in _jit_compile
    with_cuda=with_cuda)
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 866, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 962, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'build': b"[1/2] /usr/local/cuda:/bin/nvcc -DTORCH_EXTENSION_NAME=build -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/include -isystem /home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/include/TH -isystem /home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda:/include -isystem /home/wyf/anaconda3/envs/Im3D/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home/data4t/wyf/Implicit3DUnderstanding/external/pyTorchChamferDistance/chamfer_distance/chamfer_distance.cu -o chamfer_distance.cuda.o\nFAILED: chamfer_distance.cuda.o \n/usr/local/cuda:/bin/nvcc -DTORCH_EXTENSION_NAME=build -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/include -isystem /home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/include/TH -isystem /home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda:/include -isystem /home/wyf/anaconda3/envs/Im3D/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home/data4t/wyf/Implicit3DUnderstanding/external/pyTorchChamferDistance/chamfer_distance/chamfer_distance.cu -o chamfer_distance.cuda.o\n/bin/sh: 1: /usr/local/cuda:/bin/nvcc: not found\nninja: build stopped: subcommand failed.\n"

**Then I changed the ['ninja', '-v'] in `anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/utils/cpp_extension.py` to ['ninja', '--version']. And the error changed.**

②Traceback (most recent call last):
  File "main.py", line 8, in <module>
    import train, test,demo
  File "/home/data4t/wyf/Implicit3DUnderstanding/train.py", line 4, in <module>
    from models.optimizers import load_optimizer, load_scheduler
  File "/home/data4t/wyf/Implicit3DUnderstanding/models/__init__.py", line 1, in <module>
    from . import total3d, mgnet, ldif
  File "/home/data4t/wyf/Implicit3DUnderstanding/models/total3d/__init__.py", line 1, in <module>
    from . import modules, training, config, dataloader
  File "/home/data4t/wyf/Implicit3DUnderstanding/models/total3d/modules/__init__.py", line 1, in <module>
    from .network import TOTAL3D
  File "/home/data4t/wyf/Implicit3DUnderstanding/models/total3d/modules/network.py", line 12, in <module>
    from models.loss import get_phy_loss_samples
  File "/home/data4t/wyf/Implicit3DUnderstanding/models/loss.py", line 8, in <module>
    from external.pyTorchChamferDistance.chamfer_distance import ChamferDistance
  File "/home/data4t/wyf/Implicit3DUnderstanding/external/pyTorchChamferDistance/chamfer_distance/__init__.py", line 3, in <module>
    from .chamfer_distance import ChamferDistance
  File "/home/data4t/wyf/Implicit3DUnderstanding/external/pyTorchChamferDistance/chamfer_distance/chamfer_distance.py", line 8, in <module>
    build_directory="external/pyTorchChamferDistance/build")
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 824, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 967, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'build'

**It seems that the installation of module "chamfer_distance" has failed. So I used the command `pip install git+'https://github.com/otaheri/chamfer_distance'` to install the module by myself and changed the 8th line in `Implicit3DUnderstanding/models/loss.py` to `from chamfer_distance import ChamferDistance`. Then I got the following error:**

③Traceback (most recent call last):
  File "main.py", line 8, in <module>
    import train, test,demo
  File "/home/data4t/wyf/Implicit3DUnderstanding/train.py", line 4, in <module>
    from models.optimizers import load_optimizer, load_scheduler
  File "/home/data4t/wyf/Implicit3DUnderstanding/models/__init__.py", line 1, in <module>
    from . import total3d, mgnet, ldif
  File "/home/data4t/wyf/Implicit3DUnderstanding/models/total3d/__init__.py", line 1, in <module>
    from . import modules, training, config, dataloader
  File "/home/data4t/wyf/Implicit3DUnderstanding/models/total3d/modules/__init__.py", line 1, in <module>
    from .network import TOTAL3D
  File "/home/data4t/wyf/Implicit3DUnderstanding/models/total3d/modules/network.py", line 12, in <module>
    from models.loss import get_phy_loss_samples
  File "/home/data4t/wyf/Implicit3DUnderstanding/models/loss.py", line 9, in <module>
    from chamfer_distance import ChamferDistance
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/chamfer_distance/__init__.py", line 1, in <module>
    from .chamfer_distance import ChamferDistance
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/chamfer_distance/chamfer_distance.py", line 10, in <module>
    f_path + '/chamfer_distance.cu'])
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 824, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 967, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/wyf/anaconda3/envs/Im3D/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'cd'

**So far,I have no idea about the errors. Would you like to give me any suggestions? Thank you ver much!My configuration is as follows.**

- `nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 9.0, V9.0.176`
-`gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
g++ (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010`
`NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2 `

- `ninja --version
1.10.0.git.kitware.jobserver-1`

- ` packages in environment at /home/wyf/anaconda3/envs/Im3D:

 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
blas                      1.0                         mkl    conda-forge
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py36h5fab9bb_1    conda-forge
cffi                      1.14.0           py36he30daa8_1  
chardet                   3.0.4                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
cloudpickle               1.6.0                      py_0    conda-forge
cmake                     3.16.3               h28c56e5_0    conda-forge
configparser              5.0.0                    pypi_0    pypi
cudatoolkit               9.0                  h13b8566_0  
curl                      7.69.1               hbc83047_0  
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.21          py36he6710b0_0  
cytoolz                   0.11.0           py36h8c4c3a4_0    conda-forge
dask-core                 2.28.0                     py_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
docker-pycreds            0.4.0                    pypi_0    pypi
enum34                    1.1.10           py36h9f0ad1d_1    conda-forge
expat                     2.2.6                he6710b0_0  
freetype                  2.9.1                h8a8886c_1  
future                    0.18.2                   py36_1  
geos                      3.8.0                he6710b0_0  
gitdb                     4.0.5                    pypi_0    pypi
gitpython                 3.1.8                    pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
hdf4                      4.2.13               h3ca952b_2  
hdf5                      1.10.4               hb1b8bf9_0  
icu                       58.2                 he6710b0_3  
idna                      2.10                     pypi_0    pypi
imagecodecs-lite          2019.12.3        py36h785e9b2_1    conda-forge
imageio                   2.9.0                      py_0    conda-forge
intel-openmp              2020.1                      217  
jellyfish                 0.8.2                    pypi_0    pypi
joblib                    0.16.0                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
jsoncpp                   1.8.4                hfd86e86_0  
kiwisolver                1.2.0            py36hdb11119_0    conda-forge
krb5                      1.17.1               h173b8e3_0  
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libcurl                   7.69.1               h20c2e04_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libnetcdf                 4.6.1                h11d0813_2  
libogg                    1.3.2                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtheora                 1.1.1                h5ab3b9f_1  
libtiff                   4.1.0                h2733197_0  
libuv                     1.40.0               hd18ef5c_0    conda-forge
libvorbis                 1.3.6                h7b6447c_0  
libxml2                   2.9.10               he19cac6_1  
lz4-c                     1.8.1.2              h14c3975_0  
matplotlib                3.2.2                    pypi_0    pypi
mkl                       2020.1                      217  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.0.15           py36ha843d7b_0  
mkl_random                1.1.1            py36h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
networkx                  2.5                        py_0    conda-forge
ninja                     1.10.0.post1             pypi_0    pypi
numpy                     1.18.1           py36h4f9e942_0  
numpy-base                1.18.1           py36hde5b4d6_1  
olefile                   0.46                     py36_0  
opencv-python             4.2.0.34                 pypi_0    pypi
openssl                   1.1.1h               h516909a_0    conda-forge
pandas                    1.0.5            py36h0573a6f_0  
pathlib                   1.0.1            py36h9f0ad1d_2    conda-forge
pathtools                 0.1.2                    pypi_0    pypi
pillow                    7.1.2            py36hb39fc2d_0  
pip                       20.0.2                   py36_3  
promise                   2.3                      pypi_0    pypi
protobuf                  3.13.0                   pypi_0    pypi
psutil                    5.7.2                    pypi_0    pypi
pycparser                 2.20                       py_2  
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1                    pypi_0    pypi
python                    3.6.10               h7579374_2  
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytorch                   1.1.0           py3.6_cuda9.0.176_cudnn7.5.1_0    pytorch
pytz                      2020.1                     py_0  
pywavelets                1.1.1            py36h68bb277_2    conda-forge
pyyaml                    5.3.1            py36h7b6447c_0  
readline                  8.0                  h7b6447c_0  
requests                  2.24.0                   pypi_0    pypi
rhash                     1.4.0                h36c2ea0_0    conda-forge
scikit-image              0.17.2           py36h7c3b610_2    conda-forge
scipy                     1.4.1            py36h0b6359f_0  
seaborn                   0.10.1                   pypi_0    pypi
sentry-sdk                0.17.8                   pypi_0    pypi
setuptools                47.1.1                   py36_0  
shapely                   1.7.1            py36h98ec03d_0  
shortuuid                 1.0.1                    pypi_0    pypi
six                       1.15.0                     py_0  
smmap                     3.0.4                    pypi_0    pypi
sqlite                    3.31.1               h62c20be_1  
subprocess32              3.5.4                    pypi_0    pypi
tbb                       2020.0               hfd86e86_0  
tifffile                  2019.7.26.2              py36_0    conda-forge
tk                        8.6.8                hbc83047_0  
toolz                     0.11.1                     py_0    conda-forge
torchvision               0.3.0           py36_cu9.0.176_1    pytorch
tornado                   6.0.4            py36h8c4c3a4_1    conda-forge
tqdm                      4.49.0                     py_0  
trimesh                   3.8.10                   pypi_0    pypi
urllib3                   1.25.10                  pypi_0    pypi
vtk                       8.2.0           py36haa4764d_200  
wandb                     0.10.8                   pypi_0    pypi
watchdog                  0.10.3                   pypi_0    pypi
wheel                     0.34.2                   py36_0    conda-forge
xz                        5.2.5                h7b6447c_0  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0 `

**Comment by w1246410140** [comment]
OK！I have solved this problem by copying the folder `pyTorchChamferDistance` in project [Total3DUnderstanding](https://github.com/yinyunie/Total3DUnderstanding/tree/master/external)

**Comment by chengzhag** [comment]
Thanks for sharing your experience in solving the problem! I've added the prebuilt files from Total3DUnderstanding in the [latest commit](https://github.com/chengzhag/Implicit3DUnderstanding/commit/994b32aa1dbd6147b87283a1782f10e943e3df78).
