### ISSUE TITLE
the pretrained checkpoint of Total3DUnderstanding for ODN

### ISSUE THREAD

**Issue by w1246410140** [chengzhag/Implicit3DUnderstanding#4]
Hello!
Is the [link](https://livebournemouthac-my.sharepoint.com/:u:/g/personal/ynie_bournemouth_ac_uk/EcA66Nb1aI1KitzX7avbE10BiHGzovf3rqQebeJHmFB4QA?e=4hE8zv) of the pretrained checkpoint of Total3DUnderstanding for ODN in **Training and Testing** wrong?
I find it is same as the link of the preprocess SUN-RGBD data in **Data preparation**

**Comment by chengzhag** [comment]
Hi. Thanks for your response! The link is fixed in the latest commit.

**Comment by w1246410140** [comment]
Thx!
