### ISSUE TITLE
Testing typo 

### ISSUE THREAD

**Issue by mertkiray** [chengzhag/Implicit3DUnderstanding#6]
In testing section you said  In case you want to test LIEN+LDIF or full model by yourself:

`python main.py out/[ldif/total3d]/[start_time]/model_best.pth --mode test
`
But I think it should be 
`python main.py out/[ldif/total3d]/[start_time]/out_config.yaml --mode test
`

**Comment by chengzhag** [comment]
Thanks for pointing it out! A new update with the fix has been committed to the repo.
