### ISSUE TITLE
librenderer.render() (glViewport) throws segfault

### ISSUE THREAD

**Issue by zhusz** [chengzhag/Implicit3DUnderstanding#9]
Hi Cheng,

Thanks for your high quality code base for great results and nice summary of 3D toolbox. I wish to turn to you for help on one issue of segfault.

I encountered the problem of segfault when preprocessing the pix3d data. The segfault comes from librenderer.render when producing the depths. A closer check into the C code indicates that it is the [glViewport](https://github.com/chengzhag/Implicit3DUnderstanding/blob/main/external/mesh_fusion/librender/offscreen.cpp#L131) function that throws the segfault. I tried to run the [test](https://github.com/chengzhag/Implicit3DUnderstanding/blob/main/external/mesh_fusion/librender/test.py) and also encountered the segfault from the same place. I believe I have carefully installed the OpenGL, GLUT and GLEW packages through apt install and it is pretty hard to understand why the glViewport would throw the segfault. I used the headless mode with the xvfb utility. May I know if you have ever encountered the same problem and do you have any clues on this? Many thanks for your time!

**Comment by chengzhag** [comment]
Hi Shizhan,

Sorry but I have not encountered this kind of problem before. 

The [mesh_fusion](https://github.com/davidstutz/mesh-fusion) toolbox is provided by _Learning 3D Shape Completion under Weak Supervision_ with detailed descriptions. Maybe you can find more information about how to solve the problem.

Hope this helps.

**Comment by zhusz** [comment]
Hi Cheng,

Thanks for your prompt reply! :-) Since I am mainly eager for the processed data (as for the visualization part I can use my own rendering codes), is there chances that the processed data under "data/pix3d/ldif" be release? That would be huge help. :-)

**Comment by chengzhag** [comment]
Hi Shizhan,

The processing steps mentioned in our README should not involve visualization. However, the mesh_fusion toolbox does use a depth renderer to merge an SDF for watertight mesh generation (I suppose). 

Sorry that processed data cannot be released in any case, as what the agreement of ShapeNet dataset supposes.

I suggest checking the output of `python project.py build` to see if there is anything wrong with the compiling of the toolbox. Notice that the process needs higher privilege while installing packages.

If the problem persists, maybe try to reach the mesh_fusion toolbox provider for help?

**Comment by zhusz** [comment]
Thanks Cheng! No worries we resolved it with virtualGL. Thanks a lot for your help! :-)
